// Generated by CoffeeScript 1.6.3
(function() {
  angular.module('bc.active-notification', []).service("Notifications", function($rootScope) {
    $rootScope.notifications = [];
    this.all = function() {
      return $rootScope.notifications;
    };
    this.unread = function() {
      var notification, unread, _i, _len, _ref;
      unread = [];
      _ref = $rootScope.notifications;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        notification = _ref[_i];
        if (!notification.read) {
          unread.push(notification);
        }
      }
      return unread;
    };
    this.read = function() {
      var notification, read, _i, _len, _ref;
      read = [];
      _ref = $rootScope.notifications;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        notification = _ref[_i];
        if (notification.read) {
          read.push(notification);
        }
      }
      return read;
    };
    this.markAllAsRead = function() {
      var notification, _i, _len, _ref;
      _ref = $rootScope.notifications;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        notification = _ref[_i];
        notification.read = true;
      }
    };
    this.markAsRead = function(notification) {
      var notif, _i, _len, _ref, _results;
      _ref = $rootScope.notifications;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        notif = _ref[_i];
        if (notif.id === notification.id) {
          _results.push(notif.read = true);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };
    this.show = function(notification) {
      $rootScope.notifications.unshift(notification);
    };
  });

  return;

}).call(this);
